// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskAPI;

namespace TaskAPI.Migrations
{
    [DbContext(typeof(DatabaseTaskAPI))]
    [Migration("20190720140010_Update")]
    partial class Update
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TaskAPI.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("TaskAPI.Models.Photo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Path");

                    b.Property<int?>("TaskID");

                    b.HasKey("ID");

                    b.HasIndex("TaskID");

                    b.ToTable("Photo");
                });

            modelBuilder.Entity("TaskAPI.Models.Task", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryID");

                    b.Property<DateTime>("DateTime");

                    b.Property<string>("Description");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<int>("House");

                    b.Property<int?>("TaskStatus");

                    b.Property<int>("Worker");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Task");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Task");
                });

            modelBuilder.Entity("TaskAPI.Models.HistoryTask", b =>
                {
                    b.HasBaseType("TaskAPI.Models.Task");

                    b.Property<int?>("OriginalTaskID");

                    b.HasIndex("OriginalTaskID");

                    b.HasDiscriminator().HasValue("HistoryTask");
                });

            modelBuilder.Entity("TaskAPI.Models.Photo", b =>
                {
                    b.HasOne("TaskAPI.Models.Task")
                        .WithMany("Photos")
                        .HasForeignKey("TaskID");
                });

            modelBuilder.Entity("TaskAPI.Models.Task", b =>
                {
                    b.HasOne("TaskAPI.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID");
                });

            modelBuilder.Entity("TaskAPI.Models.HistoryTask", b =>
                {
                    b.HasOne("TaskAPI.Models.Task", "OriginalTask")
                        .WithMany("HistoryTasks")
                        .HasForeignKey("OriginalTaskID");
                });
#pragma warning restore 612, 618
        }
    }
}
