// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskAPI;

namespace TaskAPI.Migrations
{
    [DbContext(typeof(DatabaseTaskAPI))]
    partial class DatabaseTaskAPIModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CommonLibrary.Models.Photo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Image");

                    b.Property<int?>("TaskID");

                    b.Property<int?>("TaskID1");

                    b.HasKey("ID");

                    b.HasIndex("TaskID");

                    b.HasIndex("TaskID1");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("CommonLibrary.Models.Task", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Category");

                    b.Property<string>("Comment");

                    b.Property<int>("Creator");

                    b.Property<DateTime>("DateTime");

                    b.Property<string>("Description");

                    b.Property<int>("House");

                    b.Property<string>("Name");

                    b.Property<int>("Rate");

                    b.Property<int?>("TaskStatus");

                    b.Property<DateTime>("TimeWork");

                    b.Property<int>("Worker");

                    b.HasKey("ID");

                    b.ToTable("Task");
                });

            modelBuilder.Entity("CommonLibrary.Models.Photo", b =>
                {
                    b.HasOne("CommonLibrary.Models.Task")
                        .WithMany("Photos")
                        .HasForeignKey("TaskID");

                    b.HasOne("CommonLibrary.Models.Task")
                        .WithMany("PhotosResult")
                        .HasForeignKey("TaskID1");
                });
#pragma warning restore 612, 618
        }
    }
}
